#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
backend=(ROOT/"cloud-functions/api/creator/[[default]].js").read_text(encoding="utf-8")
frontend=(ROOT/"web/creator.js").read_text(encoding="utf-8")
page=(ROOT/"web/creator.html").read_text(encoding="utf-8")
package=json.loads((ROOT/"package.json").read_text(encoding="utf-8"))
def require(value,message):
    if not value: raise AssertionError(message)
require(package["dependencies"].get("@noble/hashes")=="2.4.0","Argon2 dependency must be pinned")
require("argon2id" in backend and "m < 19456" in backend and "t < 2" in backend,"Argon2id minimums are missing")
require("verifyTotp" in backend and 'createHmac("sha1"' in backend,"TOTP verification is missing")
require("HttpOnly; Secure; SameSite=Strict" in backend,"Cookie flags are incomplete")
require("IDLE_MS = 30" in backend and "ABSOLUTE_MS = 8" in backend,"Session timeouts are incomplete")
require("MAX_FAILURES = 5" in backend and "LOCKOUT_MS = 15" in backend,"Login lockout is incomplete")
require('accountRateKey' in backend and '"creator-account"' in backend,"Creator lockout must use an account-stable key behind proxies")
require('rate.locked_until > now ? 429 : 401' in backend,"The threshold attempt must activate lockout immediately")
require("x-csrf-token" in backend and "csrf_hash" in backend,"CSRF protection is missing")
require("secretBytes" in backend and "typeof secret.value" in backend and "typeof secret.getValue" in backend,"EdgeOne secret wrappers are not normalized")
require("process.env.ADMIN_SESSION_SECRET || context.env?.ADMIN_SESSION_SECRET" in backend,"Node environment string must take precedence")
require("activeSession(context.request, blob, cfg.sessionSecret)" in backend,"Session verification must receive only the signing secret")
require("login_success" in backend and "login_failure" in backend and '"logout"' in backend,"Audit events are incomplete")
require("localStorage" not in frontend and "sessionStorage" not in frontend,"Web Storage must not hold sessions")
require('autocomplete="current-password"' in page and 'autocomplete="one-time-code"' in page,"Login autocomplete semantics are missing")
require('blob.list({ prefix: "jobs/"' in backend,"Creator dashboard must aggregate stored jobs")
require('path === "/api/creator/export"' in backend and "verifyCsrf(context.request, cfg, active)" in backend,"Export must be authenticated and CSRF protected")
require('record_count' in backend and 'record_hashes' in backend and 'payload_sha256' in backend,"Export integrity manifest is incomplete")
require('createHash("sha256")' in backend and 'data_export' in backend,"Export hashing or audit event is missing")
require('passwordHash' not in backend[backend.find('function exportJob'):backend.find('function sha256')],"Export must not include credential material")
require('id="creator-export"' in page and 'id="metric-jobs"' in page,"Creator dashboard controls are incomplete")
require('URL.createObjectURL' in frontend and '/api/creator/export' in frontend,"Browser export download is missing")
print("creator auth validation: PASS")
