const loginView=document.querySelector("#login-view"),dashboardView=document.querySelector("#dashboard-view"),form=document.querySelector("#creator-login"),error=document.querySelector("#creator-error"),status=document.querySelector("#creator-status"),logout=document.querySelector("#creator-logout"),exportButton=document.querySelector("#creator-export"),restoreButton=document.querySelector("#creator-restore"),backupPassphrase=document.querySelector("#backup-passphrase"),backupFile=document.querySelector("#backup-file"),exportStatus=document.querySelector("#export-status");let csrf="";
function showLogin(message=""){csrf="";loginView.hidden=false;dashboardView.hidden=true;error.textContent=message;}
async function showDashboard(session){csrf=session.csrf;loginView.hidden=true;dashboardView.hidden=false;const response=await fetch("/api/creator/summary",{credentials:"same-origin"});const data=await response.json();if(!response.ok)throw new Error(data.error||"无法读取创建者状态");const metrics=data.metrics||{};document.querySelector("#metric-jobs").textContent=metrics.total_jobs??0;document.querySelector("#metric-completed").textContent=metrics.by_status?.completed??0;document.querySelector("#metric-sources").textContent=metrics.total_sources??0;document.querySelector("#metric-cost").textContent=`¥${Number(metrics.estimated_cost_cny||0).toFixed(4)}`;status.textContent="登录保护与安全汇总已启用；EPO 专利接口等待账号审批。";}
async function restore(){try{const response=await fetch("/api/creator/session",{credentials:"same-origin"});if(response.status===503)return showLogin("创建者鉴权尚未配置，普通调研功能不受影响。");if(!response.ok)return showLogin();await showDashboard(await response.json());}catch{showLogin("暂时无法连接创建者鉴权服务。");}}
form.addEventListener("submit",async(event)=>{event.preventDefault();error.textContent="";const button=form.querySelector("button");button.disabled=true;try{const response=await fetch("/api/creator/login",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();if(!response.ok)throw new Error(data.error||"登录失败");form.reset();await showDashboard(data);}catch(problem){error.textContent=problem.message;}finally{button.disabled=false;}});
logout.addEventListener("click",async()=>{try{await fetch("/api/creator/logout",{method:"POST",credentials:"same-origin",headers:{"X-CSRF-Token":csrf}});}finally{showLogin("已安全退出。");}});restore();
const encoder=new TextEncoder(),decoder=new TextDecoder();
function bytesToBase64(value){let text="";for(const byte of value)text+=String.fromCharCode(byte);return btoa(text);}
function base64ToBytes(value){const text=atob(value),bytes=new Uint8Array(text.length);for(let i=0;i<text.length;i+=1)bytes[i]=text.charCodeAt(i);return bytes;}
async function backupKey(passphrase,salt,usage){const material=await crypto.subtle.importKey("raw",encoder.encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt,iterations:310000},material,{name:"AES-GCM",length:256},false,[usage]);}
async function encryptBackup(data,passphrase){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await backupKey(passphrase,salt,"encrypt"),ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,encoder.encode(JSON.stringify(data)));return{format:"lsrw-encrypted-backup",version:1,kdf:{name:"PBKDF2",hash:"SHA-256",iterations:310000,salt:bytesToBase64(salt)},cipher:{name:"AES-GCM",key_bits:256,iv:bytesToBase64(iv)},ciphertext:bytesToBase64(new Uint8Array(ciphertext))};}
async function decryptBackup(envelope,passphrase){if(envelope?.format!=="lsrw-encrypted-backup"||envelope?.version!==1||envelope?.kdf?.iterations!==310000||envelope?.cipher?.name!=="AES-GCM")throw new Error("备份格式或加密参数不受支持");const key=await backupKey(passphrase,base64ToBytes(envelope.kdf.salt),"decrypt"),plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv:base64ToBytes(envelope.cipher.iv)},key,base64ToBytes(envelope.ciphertext));return JSON.parse(decoder.decode(plaintext));}
async function sha256(value){const digest=await crypto.subtle.digest("SHA-256",encoder.encode(JSON.stringify(value)));return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,"0")).join("");}
async function verifyBackup(data){const records=data.records||[],manifest=data.manifest||{};if(manifest.record_count!==records.length||manifest.record_hashes?.length!==records.length)throw new Error("备份记录数量不匹配");for(let index=0;index<records.length;index+=1){if(manifest.record_hashes[index]?.id!==records[index].id||manifest.record_hashes[index]?.sha256!==await sha256(records[index]))throw new Error("备份记录校验失败");}const payload={schema_version:data.schema_version,generated_at:data.generated_at,records};if(manifest.payload_sha256!==await sha256(payload))throw new Error("备份整体校验失败");return records.length;}
exportButton.addEventListener("click",async()=>{exportButton.disabled=true;exportStatus.textContent="正在生成并加密……";try{const passphrase=backupPassphrase.value;if(passphrase.length<16)throw new Error("请先输入至少 16 位备份口令");const response=await fetch("/api/creator/export",{method:"POST",credentials:"same-origin",headers:{"X-CSRF-Token":csrf}});const data=await response.json();if(!response.ok)throw new Error(data.error||"导出失败");await verifyBackup(data);const envelope=await encryptBackup(data,passphrase),blob=new Blob([JSON.stringify(envelope,null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`life-science-workbench-backup-${new Date().toISOString().slice(0,10)}.encrypted.json`;link.click();URL.revokeObjectURL(link.href);backupPassphrase.value="";exportStatus.textContent=`已加密备份 ${data.manifest.record_count} 条记录。请把文件和口令分开保存。`;}catch(problem){exportStatus.textContent=problem.message;}finally{exportButton.disabled=false;}});
restoreButton.addEventListener("click",async()=>{restoreButton.disabled=true;exportStatus.textContent="正在隔离验证……";try{const passphrase=backupPassphrase.value,file=backupFile.files?.[0];if(passphrase.length<16)throw new Error("请输入该备份的口令");if(!file)throw new Error("请选择加密备份文件");if(file.size>25*1024*1024)throw new Error("备份文件超过 25 MB 安全上限");const envelope=JSON.parse(await file.text()),data=await decryptBackup(envelope,passphrase),count=await verifyBackup(data);backupPassphrase.value="";backupFile.value="";exportStatus.textContent=`恢复演练通过：${count} 条记录完整；验证数据已从页面释放，未写入线上。`;}catch(problem){exportStatus.textContent=problem.message;}finally{restoreButton.disabled=false;}});
